### ISSUE TITLE
Setup develop branch and follow a branching model 

### ISSUE THREAD

**Issue by goodmami** [goodmami/pydelphin#34]
I should stop pushing features and fixes directly to master. See here: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by alvations** [comment]
thumbs up for the link. And I should do the same for my repo =)

**Comment by goodmami** [comment]
Thanks. I think I got the link from NLTK, which uses the same model.

**Comment by goodmami** [comment]
pyDelphin now has a `develop` branch, so I guess this is complete as long as contributors follow the guidelines (which are now in the CONTRIBUTING.md file)
